version: '3.9'

services:
  ntfy:
    container_name: ntfy
    image: binwiederhier/ntfy:latest
    environment:
      - TZ=Asia/Kuching
    volumes:
      - /data/ntfy/cache:/var/cache/ntfy:rw
      - /data/ntfy:/etc/ntfy:rw
    ports:
      - 6741:80
    command:
      - serve
    healthcheck:
        test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
        interval: 60s
        timeout: 10s
        retries: 3
        start_period: 40s
    restart: unless-stopped